#### Pandas - Dataframe and Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
import pandas as pd

In [4]:
# Series
## A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series\n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [2]:
# create a series from dictionary

data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)

print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
data = [10, 20, 30]
index = ['a','b','c']

print(pd.Series(data, index=index))

a    10
b    20
c    30
dtype: int64

In [53]:
# DataFrame
## create a dataframe from dictionary of list

data = {
    'Name': ['Shyam', 'Oggy', 'Ben'],
    'Age': [22, 25, 36],
    'City': ['Ranchi', 'New York', 'Florida']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  Shyam   22    Ranchi
1   Oggy   25  New York
2    Ben   36   Florida
<class 'pandas.DataFrame'>

In [9]:
import numpy as np
print(np.array(df))

[['Shyam' 22 'Ranchi']
 ['Oggy' 25 'New York']
 ['Ben' 36 'Florida']]

In [10]:
# Create a dataframe from a list of dictionaries

data = [
    {'Name': 'Shyam', 'Age': 22, 'City': 'Ranchi'},
    {'Name': 'Oggy', 'Age': 34, 'City': 'Ranchi'},
    {'Name': 'Jack', 'Age': 40, 'City': 'Ranchi'},
    {'Name': 'Ben', 'Age': 35, 'City': 'Ranchi'}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age    City
0  Shyam   22  Ranchi
1   Oggy   34  Ranchi
2   Jack   40  Ranchi
3    Ben   35  Ranchi
<class 'pandas.DataFrame'>

In [15]:
df = pd.read_csv('sales_practice_dataset.csv')
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        C    3.0  Product1  525.0  South
1  2023-01-02        A   31.0  Product2  646.0   West
2  2023-01-03        C   40.0  Product2  401.0  South
3  2023-01-04        C   36.0  Product2  680.0   West
4  2023-01-05        A   24.0  Product2  448.0   West

In [16]:
df.tail()

           Date Category  Value   Product  Sales Region
995  2025-09-22        B    6.0  Product3  756.0  North
996  2025-09-23        B    9.0  Product1  474.0   West
997  2025-09-24        C    6.0  Product3  261.0  South
998  2025-09-25        C   73.0  Product1    NaN  North
999  2025-09-26        A   95.0  Product3  479.0   East

In [20]:
# Accessing data from dataframe
df

    Name  Age      City
0  Shyam   22    Ranchi
1   Oggy   25  New York
2    Ben   36   Florida

In [24]:
print(type(df['Name']))
df['Name']

<class 'pandas.Series'>

0    Shyam
1     Oggy
2      Ben
Name: Name, dtype: str

In [ ]:
df.loc[0] # row index

Name     Shyam
Age         22
City    Ranchi
Name: 0, dtype: object

In [ ]:
df.iloc[0] # column index

Name     Shyam
Age         22
City    Ranchi
Name: 0, dtype: object

In [40]:
# Accessing a specified element
df.at[2, 'Age']

np.int64(36)

In [41]:
df.at[2, 'Name']

'Ben'

In [42]:
# Accessing a specified element using iat
df.iat[2, 2]

'Florida'

In [44]:
# Data Manipulation with DataFrame
df

    Name  Age      City
0  Shyam   22    Ranchi
1   Oggy   25  New York
2    Ben   36   Florida

In [ ]:
# Adding a column
df['Salary'] = [50000, 60000, 70000]
df

    Name  Age      City  Salary
0  Shyam   22    Ranchi   50000
1   Oggy   25  New York   60000
2    Ben   36   Florida   70000

In [48]:
# Remove a column
df.drop('Salary', axis=1, inplace=True) # ? axis = 0 for rows (by default) and axis = 1 for columns

# ! by default the drop() does not actualy removes the column from the df.
# ? in order to save it we use inplace = True

In [49]:
df

    Name  Age      City
0  Shyam   22    Ranchi
1   Oggy   25  New York
2    Ben   36   Florida

In [54]:
# Add age to the column
df['Age'] = df['Age'] + 1
df

    Name  Age      City
0  Shyam   23    Ranchi
1   Oggy   26  New York
2    Ben   37   Florida

In [57]:
df.drop(0, inplace=True)

In [58]:
df

   Name  Age      City
1  Oggy   26  New York
2   Ben   37   Florida

In [59]:
df = pd.read_csv('sales_practice_dataset.csv')
df.head(10)

         Date Category  Value   Product  Sales Region
0  2023-01-01        C    3.0  Product1  525.0  South
1  2023-01-02        A   31.0  Product2  646.0   West
2  2023-01-03        C   40.0  Product2  401.0  South
3  2023-01-04        C   36.0  Product2  680.0   West
4  2023-01-05        A   24.0  Product2  448.0   West
5  2023-01-06        A   95.0  Product3  931.0   West
6  2023-01-07        C    6.0  Product3  148.0   East
7  2023-01-08        B   66.0  Product3  173.0  South
8  2023-01-09        C   84.0  Product3  803.0  North
9  2023-01-10        C   92.0  Product3  360.0  North

In [62]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

Data types:
 Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object

In [65]:
# Describe the DataFrame
print("Statistical summary:")
df.describe()

Statistical summary:

            Value       Sales
count  960.000000  960.000000
mean    49.721875  566.967708
std     28.983127  251.630379
min      1.000000  100.000000
25%     25.000000  361.000000
50%     49.000000  577.000000
75%     75.000000  771.250000
max     99.000000  998.000000

In [64]:
# Group by a column and perform an aggregation
grouped = df.groupby('Category')['Value'].mean()
print("Mean value by category:\n", grouped)

Mean value by category:
 Category
A    51.380814
B    48.377419
C    49.218954
Name: Value, dtype: float64